version: '3.4'

services:
  tmsbe:
    image: tmsbe
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
  postgres:
    image: postgres:latest
    container_name: tmsbe-db
    environment:
      POSTGRES_DB: tms_db
      POSTGRES_USER: tmsbeUser
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: